# Allow policy
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-allow
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow
  process:
    matchPaths:
      - path: /usr/games/fortune
      - path: /usr/games/cowsay
  file:
    matchPaths:
      - path: /app/wisecow.sh
        readOnly: true
    matchDirectories:
      - dir: /app/
        recursive: true
        readOnly: true
  network:
    matchProtocols:
      - protocol: TCP
        fromSource:
          - path: /bin/nc
          - path: /usr/bin/nc
  action: Allow

